name: CI

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 17 * * *'

jobs:
  check_code_format:
    name: Check code format
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/python-common

      - name: Check code format
        run: ./dev.py black-check

      - uses: ./.github/workflows/node-common
        if: always()

      - name: Check TypeScript, YAML, and JSON format
        run: npm run format:check

  check_types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/python-common

      - name: Check types
        run: ./dev.py check-types

  check_lint:
    name: Check lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/python-common

      - name: Check lint
        run: ./dev.py lint

  run_tests:
    name: Run tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
          - python-version: '3.11'
          - python-version: '3.12'
          - python-version: '3.13'
          - python-version: '3.14'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/python-common
        with:
          python-version: ${{ matrix.python-version }}
          extras-param: '--extras client --extras lambda_common --extras compute_graph'

      - name: Run tests
        run: ./dev.py coverage
        env:
          AWS_DEFAULT_REGION: ${{ vars.OSS_AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.OSS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OSS_AWS_SECRET_ACCESS_KEY }}
          INTEGRATION_TEST_BUCKET: ${{ vars.INTEGRATION_TEST_BUCKET }}
          INTEGRATION_TEST_LAMBDA_ROLE: ${{ vars.INTEGRATION_TEST_LAMBDA_ROLE }}

  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/python-common

      - name: Build the package
        run: poetry build

      - name: Upload distributable
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/
